FROM python:3.12-slim

COPY . /app

WORKDIR ./app

RUN pip install -r requirements.txt 

EXPOSE 8000

# uncomment to use the in-built Flask dev server
CMD ["python3", "main.py"]

# production server
# CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "main:app"]
