FROM postgres:16


# install pg_cron
RUN apt-get update &&  \ 
    apt-get -y install postgresql-16-cron && \ 
    apt-get clean \ 
    && rm -rf /var/lib/apt/lists/


COPY 1-init.sql /docker-entrypoint-initdb.d/

COPY 2-schema.sql /docker-entrypoint-initdb.d/

COPY 3-permissions.sql /docker-entrypoint-initdb.d/

COPY 4-load-static.sql /docker-entrypoint-initdb.d/

COPY 5-load-dynamic.sql /docker-entrypoint-initdb.d/

COPY 6-functions.sql /docker-entrypoint-initdb.d/

COPY 7-cron_schedules.sql /docker-entrypoint-initdb.d/

COPY drop.sql /utils/

COPY pg_hba.conf /utils/
