# Dockerfile.client
# For the development and testing build of the frontend client

FROM node:latest

WORKDIR /app
 
COPY package*.json ./
 
RUN npm install

COPY . .

EXPOSE 5173

# currently dpeloying via the development server
CMD ["npm", "run", "dev"]