# Dockerfile.client
# For the production build of the frontend client

FROM node:22-alpine

WORKDIR /app
 
COPY package*.json ./
 
RUN npm install

COPY . .

EXPOSE 5173

# currently dpeloying via the development server
CMD ["npm", "run", "dev"]
